# Generated by Django 5.1.2 on 2024-11-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(blank=True, max_length=200, null=True)),
                ('nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(blank=True, max_length=200, null=True)),
                ('nascimento', models.DateField()),
            ],
        ),
    ]
