# Generated by Django 5.1.2 on 2024-11-02 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alunos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
