# Generated by Django 5.1.2 on 2024-11-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alunos', '0003_curso_doadores_matricula_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='endereco',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
