# Generated by Django 5.1.2 on 2024-11-02 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alunos', '0005_agendamento_assistente_doacao_encaminha_presenca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Alunos.aluno'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Alunos.responsavel'),
        ),
        migrations.AddField(
            model_name='doacao',
            name='doador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Alunos.doadores'),
        ),
        migrations.AddField(
            model_name='encaminha',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Alunos.aluno'),
        ),
        migrations.AddField(
            model_name='encaminha',
            name='assistente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Alunos.assistente'),
        ),
        migrations.AddField(
            model_name='visitas',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Alunos.aluno'),
        ),
    ]
