# Generated by Django 5.1.2 on 2024-11-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alunos', '0006_agendamento_aluno_aluno_responsavel_doacao_doador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Alunos/'),
        ),
    ]
